### ISSUE TITLE
Some issues with SSL

### ISSUE THREAD

**Issue by atroo** [ONLYOFFICE/Docker-ONLYOFFICE-CommonServer#1]
We came across 2 problems when utilizing the docker image:

1. we tried the following combination

client -> https -> our nginx -> http -> onlyoffice nginx

everything works except the upload. When posting to https://office.atroo.de/api/2.0/files/1/upload/create_session.json it responds with:
``` javascript
{"status":1,
"statusCode":500,
"error":{"message":"The remote server returned an error: (404) Not Found.","type":"System.Net.WebException","stack":"  at System.Net.HttpWebRequest.CheckFinalStatus (System.Net.WebAsyncResult result) [0x00000] in <filename unknown>:0 \u000a  at System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData data) [0x00000] in <filename unknown>:0 ",
"hresult":-2146233079,
"data":{}}}
```
when we switched to

client -> http -> our nginx -> http -> onlyoffice nginx

Here, uploads are working. So maybe you know what could be the problem?

2. we were looking at the nginx conf in the debian package and there is no server at port 443 defined, but the image exposes this port. Does it mean it is work in progress?

We also exposed the volumes for mysql and the upload folder to persist our data. This solution is not ready for production yet, but maybe you are interested to build upon it.

Thanks in advance!

**Comment by AnaMih** [comment]
Please, try the new version of an official Docker container of OnlyOffice, which is already configured.
https://registry.hub.docker.com/u/ascensiosystemsia/onlyoffice-commonserver/
